# Generated by Django 2.0.4 on 2018-04-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.IntegerField()),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha incio contrato')),
                ('fecha_finalizacion_contrato', models.DateField(verbose_name='Fecha finalización contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Nombres')),
                ('direccion', models.CharField(max_length=60, verbose_name='Nombres')),
                ('telefono', models.CharField(max_length=10, verbose_name='Nombres')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cumpleanos', models.DateField(verbose_name='Fecha Cumpleaños')),
                ('vial', models.CharField(max_length=20, verbose_name='Vial')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_propietario', to='app.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Taxista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateField(verbose_name='Fecha vinculación')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha_nacimiento')),
                ('foto', models.ImageField(upload_to='taxista/foto', verbose_name='Foto')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('tipo_sangre', models.CharField(max_length=2, verbose_name='Tipo de sangre')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_taxista', to='app.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10, verbose_name='Marca')),
                ('placa', models.CharField(max_length=6, verbose_name='PLaca')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('numero_licencia', models.CharField(max_length=10, verbose_name='Número licencia')),
                ('linea', models.CharField(max_length=10, verbose_name='Línea')),
                ('chasis', models.CharField(max_length=10, verbose_name='Chasis')),
                ('pasajeros', models.CharField(max_length=2, verbose_name='Pasajeros')),
                ('carroceria', models.CharField(max_length=10, verbose_name='Carroceria')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('motor', models.CharField(max_length=20, verbose_name='Motor')),
                ('cilindraje', models.CharField(max_length=20, verbose_name='Cilindraje')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_vehiculo', to='app.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_empleado', to='app.Persona'),
        ),
    ]
