# Generated by Django 2.0.6 on 2018-06-06 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.IntegerField()),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha incio contrato')),
                ('fecha_finalizacion_contrato', models.DateField(verbose_name='Fecha finalización contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Nombres')),
                ('direccion', models.CharField(max_length=60, verbose_name='Nombres')),
                ('departamento', models.CharField(max_length=30, null=True, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=30, null=True, verbose_name='Municipio')),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_cumpleanos', models.DateField(verbose_name='Fecha Cumpleaños')),
                ('vial', models.CharField(max_length=20, unique=True, verbose_name='Vial')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_propietario', to='app.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Taxista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha_nacimiento')),
                ('foto', models.ImageField(upload_to='taxista/foto', verbose_name='Foto')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('tipo_sangre', models.CharField(max_length=2, verbose_name='Tipo de sangre')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_taxista', to='app.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10, verbose_name='Marca')),
                ('placa', models.CharField(max_length=6, unique=True, verbose_name='Placa')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('numero_licencia', models.CharField(max_length=10, verbose_name='Número licencia')),
                ('linea', models.CharField(max_length=10, verbose_name='Línea')),
                ('chasis', models.CharField(max_length=10, unique=True, verbose_name='Chasis')),
                ('pasajeros', models.CharField(max_length=2, verbose_name='Pasajeros')),
                ('carroceria', models.CharField(max_length=10, verbose_name='Carroceria')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('motor', models.CharField(max_length=20, unique=True, verbose_name='Motor')),
                ('cilindraje', models.CharField(max_length=20, verbose_name='Cilindraje')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_vehiculo', to='app.Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='VinculacionVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(max_length=10, unique=True, verbose_name='Radicado')),
                ('licencia', models.FileField(null=True, upload_to='vinculacion/licencia', verbose_name='Licencia')),
                ('soat', models.FileField(null=True, upload_to='vinculacion/soat', verbose_name='SOAT')),
                ('fecha_vencimiento_soat', models.DateField(null=True, verbose_name='Vencimiento SOAT')),
                ('tecnomecanica', models.FileField(null=True, upload_to='vinculacion/tecnomecanica', verbose_name='Tecnomecánica')),
                ('fecha_vencimiento_tecnomecanica', models.DateField(null=True, verbose_name='Vencimiento tecnomecánica')),
                ('targeta_operacion', models.FileField(null=True, upload_to='vinculacion/targeta_operacion', verbose_name='Targeta de operación')),
                ('fecha_vencimiento_targeta_operacion', models.DateField(null=True, verbose_name='Vencimiento targeta de operación')),
                ('seguro_accidente_personal', models.FileField(null=True, upload_to='vinculacion/seguro_accidente', verbose_name='Seguro de accidente personal')),
                ('fecha_vencimiento_seguro_accidente', models.DateField(null=True, verbose_name='Vencimiento seguro accidente personal')),
                ('seguro_extracontractual', models.FileField(null=True, upload_to='vinculacion/seguro_extra', verbose_name='Seguro extracontractual')),
                ('fecha_vencimiento_seguro_extracontractual', models.DateField(null=True, verbose_name='Vencimiento seguro extracontractual')),
                ('seguro_contractual', models.FileField(null=True, upload_to='vinculacion/seguro_contra', verbose_name='Seguro contractual')),
                ('fecha_vencimiento_seguro_contractual', models.DateField(null=True, verbose_name='Vencimiento seguro contractual')),
                ('revision_preoperacional', models.FileField(null=True, upload_to='vinculacion/preoperacional', verbose_name='Seguro preoperacional')),
                ('rut', models.FileField(null=True, upload_to='vinculacion/rut', verbose_name='RUT')),
                ('antecedentes', models.FileField(null=True, upload_to='vinculacion/antecedetes', verbose_name='Antecendentes')),
                ('fecha_vinculacion', models.DateField(default=datetime.date.today, verbose_name='Fecha vinculación')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_vehiculo', to='app.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='taxista',
            name='vinculacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_vehiculo', to='app.VinculacionVehiculo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_empleado', to='app.Persona'),
        ),
    ]
