# Generated by Django 2.0.6 on 2018-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacionvehiculo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
