# Generated by Django 2.0.4 on 2018-04-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculacionVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(max_length=8, unique=True, verbose_name='Radicado')),
                ('licencia', models.FileField(upload_to='vinculacion/licencia', verbose_name='Licencia')),
                ('soat', models.FileField(upload_to='vinculacion/soat', verbose_name='SOAT')),
                ('fecha_vencimiento_soat', models.DateField(verbose_name='Vencimiento SOAT')),
                ('tecnomecanica', models.FileField(upload_to='vinculacion/tecnomecanica', verbose_name='Tecnomecánica')),
                ('fecha_vencimiento_tecnomecanica', models.DateField(verbose_name='Vencimiento tecnomecánica')),
                ('targeta_operacion', models.FileField(upload_to='vinculacion/targeta_operacion', verbose_name='Targeta de operación')),
                ('fecha_vencimiento_targeta_operacion', models.DateField(verbose_name='Vencimiento targeta de operación')),
                ('seguro_accidente_personal', models.FileField(upload_to='vinculacion/seguro_accidente', verbose_name='Seguro de accidente personal')),
                ('fecha_vencimiento_seguro_accidente', models.DateField(verbose_name='Vencimiento seguro accidente personal')),
                ('seguro_extracontractual', models.FileField(upload_to='vinculacion/seguro_extra', verbose_name='Seguro extracontractual')),
                ('fecha_vencimiento_seguro_extracontractual', models.DateField(verbose_name='Vencimiento seguro extracontractual')),
                ('seguro_contractual', models.FileField(upload_to='vinculacion/seguro_contra', verbose_name='Seguro contractual')),
                ('fecha_vencimiento_seguro_contractual', models.DateField(verbose_name='Vencimiento seguro contractual')),
                ('revision_preoperacional', models.FileField(upload_to='vinculacion/preoperacional', verbose_name='Seguro preoperacional')),
                ('rut', models.FileField(upload_to='vinculacion/rut', verbose_name='RUT')),
                ('antecedentes', models.FileField(upload_to='vinculacion/antecedetes', verbose_name='Antecendentes')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_vehiculo', to='app.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='taxista',
            name='vinculacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_vehiculo', to='app.VinculacionVehiculo'),
        ),
    ]
