# Generated by Django 2.0.4 on 2018-04-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180406_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='departamento',
            field=models.CharField(max_length=30, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='municipio',
            field=models.CharField(max_length=30, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, verbose_name='Placa'),
        ),
    ]
