# Generated by Django 2.0.4 on 2018-04-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180410_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='vial',
            field=models.CharField(max_length=20, unique=True, verbose_name='Vial'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chasis',
            field=models.CharField(max_length=10, unique=True, verbose_name='Chasis'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(max_length=20, unique=True, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_vehiculo', to='app.Propietario'),
        ),
    ]
