# Generated by Django 2.0.4 on 2018-04-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180412_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
