# Generated by Django 2.0.4 on 2018-05-30 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_propietario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxista',
            name='fecha_vinculacion',
        ),
        migrations.AddField(
            model_name='vinculacionvehiculo',
            name='fecha_vinculacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha vinculación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
